Repository Bambosh/unofficial-homestuck-collection, pull requests merged in 2022-02, with the labels that each got.

#268 Setup enhancement: Validate asset pack version. …
  src/App.vue
  src/assets/collection_logo.png
  src/background.js
  src/components/SystemPages/Setup.vue
Labels: documentation

#269 Mod performance improvements
  MODDING.md
  src/components/Page/Page.vue
  src/components/SystemPages/Homepage.vue
  src/components/SystemPages/Settings.vue
  src/mods.js
Labels: mods, implementation

#285 Bugfix: Validate state before attempting to extract imods
  src/background.js
  src/components/SystemPages/Setup.vue
  src/mods.js
Labels: bug

#267 Option to use native window decorations
  src/background.js
  src/components/AppMenu/AppHeader.vue
  src/components/AppMenu/TitleBar.vue
  src/components/SystemPages/Settings.vue
  src/store/localData.js
Labels: enhancement, style

#282 Page navigation from pagenav updates new reader automatically (fixes multinav bugs)
  src/background.js
  src/components/Page/PageNav.vue
  src/components/SpecialPages/TzPassword.vue
  src/components/TabFrame.vue
  src/main.js
Labels: bug

#316 Dragging
  package.json
  src/background.js
  yarn.lock
Labels: bug, style

#317 Context menu enhancements
  src/background.js
  src/components/UIElements/ContextMenu.vue
Labels: enhancement

#326 Resource path fix
  src/components/UIElements/MediaModal.vue
  src/resources.js
Labels: bug

#324 Fix double audio SWFs & scarecrowking
  src/imods/_twoToThree/mod.js
  src/imods/_twoToThree/pxs/.keepdir
  src/imods/_twoToThree/swf/03085_hq.swf
  src/imods/_twoToThree/swf/04082_hq.swf
  src/mods.js
Labels: bug

#301 v2.0.5
  .github/ISSUE_TEMPLATE/bug_report.md
  MODDING.md
  Makefile
  package.json
  src/background.js
  src/components/AppMenu/AppHeader.vue
  src/components/AppMenu/TabBar.vue
  src/components/AppMenu/TitleBar.vue
  src/components/Page/Page.vue
  src/components/Page/PageMetadata.vue
  src/components/Page/PageNav.vue
  src/components/Page/PageText.vue
  src/components/Socials/News.vue
  src/components/SpecialPages/Echidna.vue
  src/components/SpecialPages/EndOfHS.vue
  src/components/SpecialPages/Firefly.vue
  src/components/SpecialPages/TzPassword.vue
  src/components/SpecialPages/fullscreenFlash.vue
  src/components/SpecialPages/x2Combo.vue
  src/components/SpecialPages/x2ComboNav.vue
  src/components/SystemPages/Homepage.vue
  src/components/SystemPages/Search.vue
  src/components/SystemPages/Settings.vue
  src/components/SystemPages/Setup.vue
  src/components/TabFrame.vue
  src/components/UIElements/Bookmarks.vue
  src/components/UIElements/ContextMenu.vue
  src/components/UIElements/HomeRowItem.vue
  src/components/UIElements/MediaModal.vue
  src/components/UIElements/Notifications.vue
  src/components/UIElements/SubSettingsModal.vue
  src/components/UIElements/Updater.vue
  src/css/mspaThemes.scss
  src/imods/_bolin.js
  src/imods/_hqAudio.js
  src/imods/_twoToThree/mod.js
  src/imods/_twoToThree/pxs/.keepdir
  src/imods/_twoToThree/swf/03085_hq.swf
  src/imods/_twoToThree/swf/04082_hq.swf
  src/main.js
  src/mods.js
  src/resources.js
  src/store/localData.js
  vue.config.js
  yarn.lock
Labels: bug, documentation, enhancement, mods, style, implementation, awaiting approval
